### ISSUE TITLE
[require] AssertionError: path must be a string

### ISSUE THREAD

**Issue by trueter** [Pomax/react-onclickoutside#57]
4.4.0 breaks compatibility with Babel 5.
Regression introduced in https://github.com/Pomax/react-onclickoutside/pull/53. 

Error looks like this. 
```code
can't execute file: /Users/Greyson/XXX/bin/server.js
    error given was: AssertionError: path must be a string
    at Module.require (module.js:365:3)
    at require (module.js:385:17)
    at registeredComponents (/Users/Greyson/XXX/node_modules/react-datepicker/node_modules/react-onclickoutside/index.js:26:30)
    at Object.<anonymous> (/Users/Greyson/XXX/node_modules/react-datepicker/node_modules/react-onclickoutside/index.js:31:2)
    at Module._compile (module.js:435:26)
    at Module._extensions..js (module.js:442:10)
    at require.extensions.(anonymous function) (/Users/Greyson/XXX/node_modules/babel-core/lib/api/register/node.js:214:7)
    at /Users/Greyson/XXX/node_modules/webpack-isomorphic-tools/babel-transpiled-modules/tools/require hacker.js:219:64
    at webpack_isomorphic_tools.require (/Users/Greyson/XXX/node_modules/webpack-isomorphic-tools/babel-transpiled-modules/index.js:340:11)
    at /Users/Greyson/XXX/node_modules/webpack-isomorphic-tools/babel-transpiled-modules/index.js:297:18
    at Object._module3.default._extensions.(anonymous function) [as .js] (/Users/Greyson/XXX/node_modules/webpack-isomorphic-tools/babel-transpiled-modules/tools/require hacker.js:206:17)
    at Module.load (module.js:356:32)
    at Module._load (module.js:311:12)
    at Function.module._load (/Users/Greyson/XXX/node_modules/piping/lib/launcher.js:32:16)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

**Comment by mrtho1** [comment]
Seeing similar issues, see:
https://github.com/Pomax/react-onclickoutside/commit/96914ed131683d9175620534c3e789efa1dc4ca4

**Comment by jakoblind** [comment]
+1

**Comment by Pomax** [comment]
babel's currently on v6.4, though, does it still happen on that version?

**Comment by mrtho1** [comment]
We updated several libs and aren't seeing this anymore.  Wish I could be more helpful as to the specific change that 'fixed' it.

**Comment by Pomax** [comment]
no worries. If someone else runs into this still, they'll hopefully find this issue and comment on it.

**Comment by Pomax** [comment]
closing with the release of v5.0.0, if this still happens with the new hoc-only version, please file a new issue.
